name: Scrape Latest NJ Traffic Events Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * 1-5'
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://511nj.org/api/client/Map/getEventData | jq . > trafficEvents.json
    - name: Commit and push file if there is a delta
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add --all
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
